


############################################################
#  Top Level Labels
############################################################
repo:
  - ./*


############################################################
#  Documentation
############################################################
documentation:
  - "*.md"

############################################################
#  Tools + Development Items
############################################################

github:
  - .github
  - .github/*
  - .github/**/*

workflows:
  - .github/workflows/*
  - .github/workflows/**/*


############################################################
#  Tests
############################################################
tests:
  - src/test/*
  - src/test/**/*

############################################################
#  Core
############################################################

core:
  - "*.gradle"
  - "*/*.gradle"
  - "*.kts"
  - "*.jks"
  - "*.pro"

feature-activity:
  - '**/**/*.xml'

feature-activity2:
  - '**/layout/*.xml'
