


############################################################
#  Top Level Labels
############################################################
repo:
  - ./*


############################################################
#  Documentation
############################################################
documentation:
  - "*.md"


############################################################
#  Tools + Development Items
############################################################

github:
  - .github
  - .github/*
  - .github/**/*

workflows:
  - .github/workflows/*
  - .github/workflows/**/*


############################################################
#  Tests
############################################################
tests:
  - src/test/*
  - src/test/**/*

############################################################
#  Core
############################################################

core:
  - settings.gradle
  - "*.kts"
  - "*.jks"
  - "*.js"
  - "*.pro"
  - .gitattributes
  - .gitignore
  - .gitmodules
  - gradle.properties
  - detekt-baseline.xml
  - commitlint.config.js
  - settings.gradle.kts





feature:
  - app/**


