name: Build Number

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use onyxmueller/build-tag-number@v1
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}