name: Build Number

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "**"



jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Dependabot CLI
        run: gem install dependabot --no-document

      - name: Run Dependabot
        run: dependabot --version