name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["labeler"]
    types:
      - completed

jobs:

  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: labeler.yml
          name: ${{ env.BUILD_ARTIFACTS }}