name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [ "labeler" ]
    types:
      - completed

jobs:

  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: labeler.yml

      - name: Read from Downloaded Artifact
        run: |
          ls -l
          cd my-artifact
          ls -l
          labels=`cat world.txt`
          echo "${labels}"
          echo "LABELS=${cat world.txt}" >> $GITHUB_ENV
      - name: Print
        run: |
          echo "LABELS $LABELS"