name: CI notify

# Only trigger, when the build workflow succeeded
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "**"
  workflow_run:
    workflows: ["Labeler"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: notify
        run: |
          echo "ci notify"
