name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["labeler"]
    types:
      - completed

jobs:

  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Environment Variables
        shell: bash
        run: |
            ARTIFACTS_SHA=$(git rev-parse HEAD)
            BUILD_ARTIFACTS=BuildArtifacts_${ARTIFACTS_SHA}
            echo "ARTIFACTS_DIR=$ARTIFACTS_DIR" >> $GITHUB_ENV
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Build.yml
          name: ${{ env.BUILD_ARTIFACTS }}